QUESTIONS = {
    "General Knowledge": {
        "Easy": [
            {"q": "What can travel around the world while staying in a corner?", "answer": "stamp"},
            {"q": "I’m tall when I’m young, and I’m short when I’m old. What am I?", "answer": "candle"},
            {"q": "What has to be broken before you can use it?", "answer": "egg"},
            {"q": "What has many teeth but can’t bite?", "answer": "comb"},
            {"q": "What has a face and two hands but no arms or legs?", "answer": "clock"},
            {"q": "What gets wetter the more it dries?", "answer": "towel"},
            {"q": "What has words but never speaks?", "answer": "book"},
            {"q": "What has an ear but cannot hear?", "answer": "cornfield"},
            {"q": "What has a neck but no head?", "answer": "bottle"},
            {"q": "What has legs but doesn’t walk?", "answer": "table"},
            {"q": "What belongs to you but is used more by others?", "answer": "your name"},
            {"q": "What has one head, one foot, and four legs?", "answer": "bed"},
            {"q": "What can you catch but not throw?", "answer": "cold"},
            {"q": "What goes up but never comes down?", "answer": "age"},
            {"q": "What can be cracked, made, told, and played?", "answer": "joke"},
            {"q": "What is always moving but never stops?", "answer": "time"},
            {"q": "What has eyes but cannot see?", "answer": "potato"},
            {"q": "What has keys but no locks?", "answer": "piano"},
            {"q": "What runs but never walks?", "answer": "river"},
            {"q": "What has a ring but no finger?", "answer": "telephone"},
            {"q": "What has four fingers and a thumb but is not alive?", "answer": "glove"},
            {"q": "What can fill a room but takes up no space?", "answer": "light"},
            {"q": "What comes down but never goes up?", "answer": "rain"},
            {"q": "What has stripes but no clothes?", "answer": "zebra"},
            {"q": "What is black and white and read all over?", "answer": "newspaper"},
            {"q": "What has wings but cannot fly?", "answer": "penguin"},
            {"q": "What can you hold without touching it?", "answer": "your breath"},
            {"q": "What has holes but still holds water?", "answer": "sponge"},
            {"q": "What has a bed but never sleeps?", "answer": "river"},
            {"q": "What has branches but no fruit or leaves?", "answer": "bank"},
        ],
        "Medium": [
            {"q": "I speak without a mouth and hear without ears. What am I?", "answer": "echo"},
            {"q": "The more of me you take, the more you leave behind. What am I?", "answer": "footsteps"},
            {"q": "What begins with T, ends with T, and is full of T?", "answer": "teapot"},
            {"q": "I’m always in front of you but can’t be seen. What am I?", "answer": "future"},
            {"q": "I am not alive, but I can grow; I have no mouth, yet water kills me. What am I?", "answer": "fire"},
            {"q": "I fly without wings, I cry without eyes. What am I?", "answer": "cloud"},
            {"q": "The more you take from me, the bigger I get. What am I?", "answer": "hole"},
            {"q": "I am always moving forward but never backward. What am I?", "answer": "time"},
            {"q": "What gets sharper the more you use it?", "answer": "your brain"},
            {"q": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "letter M"},
            {"q": "The more you share me, the less I become. What am I?", "answer": "secret"},
            {"q": "What can fly without wings and cry without eyes?", "answer": "wind"},
            {"q": "I have keys but no locks; I open many doors. What am I?", "answer": "keyboard"},
            {"q": "The more you remove from me, the bigger I get. What am I?", "answer": "a hole"},
            {"q": "I can run but never walk. What am I?", "answer": "nose"},
            {"q": "I am always in front of you, but you can never see me. What am I?", "answer": "future"},
            {"q": "What gets smaller the more you use it?", "answer": "pencil"},
            {"q": "The more you look at me, the less you see. What am I?", "answer": "darkness"},
            {"q": "I’m not alive, but if you feed me, I grow. If you give me water, I die. What am I?", "answer": "fire"},
            {"q": "The more you take me out of me, the bigger I get. What am I?", "answer": "hole"},
            {"q": "What has roots but never grows?", "answer": "mountain"},
            {"q": "What has a head and a tail but no body?", "answer": "coin"},
            {"q": "What starts with E, ends with E, but only has one letter?", "answer": "envelope"},
            {"q": "I’m invisible, but you can feel me. I move things around you. What am I?", "answer": "air"},
            {"q": "I am always running but never move. What am I?", "answer": "clock"},
            {"q": "The more you take from me, the less I have. What am I?", "answer": "knowledge"},
            {"q": "What has many rings but no fingers?", "answer": "tree"},
            {"q": "I am found in seconds, minutes, and centuries, but not in hours, days, or years. What am I?", "answer": "letter N"},
            {"q": "I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?", "answer": "fire"},
            {"q": "What disappears when you say its name?", "answer": "silence"},
        ],
        "Hard": [
            {"q": "It has keys but no locks; it has space but no room; you can enter but can’t go outside. What is it?", "answer": "keyboard"},
            {"q": "What word is spelled incorrectly in every dictionary?", "answer": "incorrectly"},
            {"q": "The more you take from me, the bigger I get. What am I?", "answer": "hole"},
            {"q": "Forward I am heavy, backward I am not. What am I?", "answer": "ton"},
            {"q": "I’m always hungry, I must be fed. What am I?", "answer": "fire"},
            {"q": "I am taken from a mine and locked up in a wooden case. What am I?", "answer": "pencil lead"},
            {"q": "The more you take me, the more you leave behind. What am I?", "answer": "footsteps"},
            {"q": "What can fill a room and never takes up space?", "answer": "light"},
            {"q": "What disappears as soon as you say its name?", "answer": "silence"},
            {"q": "What can run but never walks, has a mouth but never talks?", "answer": "river"},
            {"q": "I am not alive but can die. What am I?", "answer": "battery"},
            {"q": "What has a heart that doesn’t beat?", "answer": "artichoke"},
            {"q": "I am the beginning of everything and the end of time and space. What am I?", "answer": "letter E"},
            {"q": "What is always old but sometimes new?", "answer": "history"},
            {"q": "What occurs once in a lifetime, twice in a moment, but never in a hundred years?", "answer": "letter M"},
            {"q": "I’m seen in the water but never get wet. What am I?", "answer": "reflection"},
            {"q": "I am always moving, yet I never leave my place. What am I?", "answer": "clock"},
            {"q": "What can be cracked, made, told, and played?", "answer": "joke"},
            {"q": "The more you use me, the duller I get. What am I?", "answer": "pencil"},
            {"q": "I am full of holes but still hold water. What am I?", "answer": "sponge"},
            {"q": "What has a tongue but never speaks?", "answer": "shoe"},
            {"q": "What runs around a house but doesn’t move?", "answer": "fence"},
            {"q": "I’m always ahead of you but never in sight. What am I?", "answer": "future"},
            {"q": "What is so fragile that saying its name breaks it?", "answer": "silence"},
            {"q": "What has roots that nobody sees, is taller than trees?", "answer": "mountain"},
            {"q": "What comes at the end of a rainbow?", "answer": "letter W"},
            {"q": "What has an end but no beginning?", "answer": "stick"},
            {"q": "What can’t be used until it’s broken?", "answer": "egg"},
            {"q": "What is always coming but never arrives?", "answer": "tomorrow"},
            {"q": "I am always hungry, always fed, and if I drink, I die. What am I?", "answer": "fire"},
        ],
    },

    "Pokémon":{
        "Easy": [
            {"q": "I am a small, yellow mouse Pokémon known for my electric cheeks. Who am I?", "answer": "Pikachu"},
            {"q": "I am a water-type turtle Pokémon. Who am I?", "answer": "Squirtle"},
            {"q": "I am a grass Pokémon with a bulb on my back. Who am I?", "answer": "Bulbasaur"},
            {"q": "I am a pink balloon-like Pokémon who sings. Who am I?", "answer": "Jigglypuff"},
            {"q": "I evolve into Raichu. Who am I?", "answer": "Pikachu"},
            {"q": "I am a fiery lizard Pokémon, the first form of Charizard. Who am I?", "answer": "Charmander"},
            {"q": "I sleep most of the time and block roads. Who am I?", "answer": "Snorlax"},
            {"q": "I love to eat honey and look like a small bear. Who am I?", "answer": "Teddiursa"},
            {"q": "I am a water-type Pokémon shaped like a fish. Who am I?", "answer": "Magikarp"},
            {"q": "I evolve from Eevee using a Water Stone. Who am I?", "answer": "Vaporeon"},
            {"q": "I am the electric bird Pokémon. Who am I?", "answer": "Zapdos"},
            {"q": "I am a psychic-type pink Pokémon that can transform. Who am I?", "answer": "Ditto"},
            {"q": "I am shaped like a ball and can explode. Who am I?", "answer": "Voltorb"},
            {"q": "I am a bug Pokémon that spins silk. Who am I?", "answer": "Caterpie"},
            {"q": "I am a yellow duck with constant headaches. Who am I?", "answer": "Psyduck"},
            {"q": "I am a horse-shaped fire Pokémon. Who am I?", "answer": "Ponyta"},
            {"q": "I am the evolution of Metapod. Who am I?", "answer": "Butterfree"},
            {"q": "I am the first Pokémon in the Pokédex. Who am I?", "answer": "Bulbasaur"},
            {"q": "I am a rock Pokémon shaped like a snake. Who am I?", "answer": "Onix"},
            {"q": "I am the Pokémon that resembles a fox and has multiple evolutions. Who am I?", "answer": "Eevee"},
            {"q": "I am a plant Pokémon with a big flower on my back. Who am I?", "answer": "Venusaur"},
            {"q": "I am a water turtle Pokémon’s final evolution. Who am I?", "answer": "Blastoise"},
            {"q": "I am a ghost Pokémon shaped like gas. Who am I?", "answer": "Gastly"},
            {"q": "I am a big pink Pokémon that heals others. Who am I?", "answer": "Chansey"},
            {"q": "I am a small bug Pokémon that evolves into Beedrill. Who am I?", "answer": "Weedle"},
            {"q": "I am known as the electric sheep Pokémon. Who am I?", "answer": "Mareep"},
            {"q": "I am a dog Pokémon with flames on my back. Who am I?", "answer": "Growlithe"},
            {"q": "I am shaped like a starfish and live in the sea. Who am I?", "answer": "Staryu"},
            {"q": "I am a bat Pokémon that appears in caves. Who am I?", "answer": "Zubat"},
            {"q": "I am a rock Pokémon that looks like a ball. Who am I?", "answer": "Geodude"},
        ],
        "Medium": [
            {"q": "I am a large, orange, fire-breathing Pokémon that resembles a dragon. Who am I?", "answer": "Charizard"},
            {"q": "I am a psychic Pokémon known for bending spoons. Who am I?", "answer": "Alakazam"},
            {"q": "I am the evolution of Eevee that uses a Water Stone. Who am I?", "answer": "Vaporeon"},
            {"q": "I am the ghost Pokémon often found in Lavender Town. Who am I?", "answer": "Gastly"},
            {"q": "I am known as the 'Sleeping Pokémon'. Who am I?", "answer": "Snorlax"},
            {"q": "I am the fiery dog Pokémon that evolves from Growlithe. Who am I?", "answer": "Arcanine"},
            {"q": "I am a dragon Pokémon and part of the legendary trio in Johto. Who am I?", "answer": "Raikou"},
            {"q": "I am the Pokémon that evolves from Magikarp. Who am I?", "answer": "Gyarados"},
            {"q": "I am the fossil Pokémon revived into a spiraled shell. Who am I?", "answer": "Omanyte"},
            {"q": "I am a three-headed bird Pokémon. Who am I?", "answer": "Dodrio"},
            {"q": "I am a grass-type Pokémon with a coconut-like head. Who am I?", "answer": "Exeggcute"},
            {"q": "I am the Pokémon with a skull on my head. Who am I?", "answer": "Cubone"},
            {"q": "I am the dragon Pokémon that evolves from Dratini. Who am I?", "answer": "Dragonair"},
            {"q": "I am the Pokémon that evolves into Jolteon. Who am I?", "answer": "Eevee"},
            {"q": "I am a psychic-type Pokémon shaped like a balloon. Who am I?", "answer": "Wobbuffet"},
            {"q": "I am the legendary electric bird Pokémon. Who am I?", "answer": "Zapdos"},
            {"q": "I am a steel Pokémon that looks like a bell. Who am I?", "answer": "Bronzong"},
            {"q": "I am the evolution of Poliwag that becomes a frog-like Pokémon. Who am I?", "answer": "Poliwhirl"},
            {"q": "I am the legendary Pokémon known as the Time Travel Pokémon. Who am I?", "answer": "Celebi"},
            {"q": "I am a Pokémon shaped like a dragonfly. Who am I?", "answer": "Yanma"},
            {"q": "I am a fire-type fox Pokémon with six tails. Who am I?", "answer": "Vulpix"},
            {"q": "I am the legendary bird that controls fire. Who am I?", "answer": "Moltres"},
            {"q": "I am the legendary water beast Pokémon of Johto. Who am I?", "answer": "Suicune"},
            {"q": "I am a plant Pokémon that evolves from Oddish. Who am I?", "answer": "Gloom"},
            {"q": "I am the legendary beast Pokémon of Johto representing thunder. Who am I?", "answer": "Raikou"},
            {"q": "I am the evolution of Abra. Who am I?", "answer": "Kadabra"},
            {"q": "I am the Pokémon with a shell that is extremely hard. Who am I?", "answer": "Cloyster"},
            {"q": "I am the Pokémon with a drill-like nose. Who am I?", "answer": "Rhyhorn"},
            {"q": "I am the legendary psychic Pokémon in Sinnoh. Who am I?", "answer": "Uxie"},
            {"q": "I am the Pokémon shaped like a rock snake. Who am I?", "answer": "Onix"},
        ],
        "Hard": [
            {"q": "This Legendary Pokémon was created by genetic manipulation. Who am I?", "answer": "Mewtwo"},
            {"q": "I am a bird trio Pokémon; I control ice. Who am I?", "answer": "Articuno"},
            {"q": "I am known as the 'Time Travel Pokémon'. Who am I?", "answer": "Celebi"},
            {"q": "I am a fossil Pokémon revived into a spiraled shell. Who am I?", "answer": "Omanyte"},
            {"q": "I am the god of Pokémon, said to have created the universe. Who am I?", "answer": "Arceus"},
            {"q": "I am the legendary Pokémon that controls time. Who am I?", "answer": "Dialga"},
            {"q": "I am the legendary Pokémon that controls space. Who am I?", "answer": "Palkia"},
            {"q": "I am the legendary Pokémon that lives in the sea and controls storms. Who am I?", "answer": "Lugia"},
            {"q": "I am the legendary bird that represents fire. Who am I?", "answer": "Moltres"},
            {"q": "I am a mythical Pokémon said to contain the DNA of every Pokémon. Who am I?", "answer": "Mew"},
            {"q": "I am the legendary Pokémon known as the 'Sky High Pokémon'. Who am I?", "answer": "Rayquaza"},
            {"q": "I am the Pokémon known as the 'DNA Pokémon'. Who am I?", "answer": "Deoxys"},
            {"q": "I am the legendary Pokémon representing land. Who am I?", "answer": "Groudon"},
            {"q": "I am the legendary Pokémon representing the sea. Who am I?", "answer": "Kyogre"},
            {"q": "I am the Pokémon that guards the Spear Pillar. Who am I?", "answer": "Giratina"},
            {"q": "I am the mythical Pokémon that evolves into different forms using plates. Who am I?", "answer": "Arceus"},
            {"q": "I am the legendary Pokémon known as the 'Wish Pokémon'. Who am I?", "answer": "Jirachi"},
            {"q": "I am a legendary bird with rainbow-colored feathers. Who am I?", "answer": "Ho-oh"},
            {"q": "I am the legendary Pokémon representing balance between time and space. Who am I?", "answer": "Giratina"},
            {"q": "I am the legendary Pokémon of the Unova region, representing ideals. Who am I?", "answer": "Reshiram"},
            {"q": "I am the legendary Pokémon of the Unova region, representing truth. Who am I?", "answer": "Zekrom"},
            {"q": "I am the Pokémon that hides in shadows and is a mythical creature. Who am I?", "answer": "Darkrai"},
            {"q": "I am the legendary Pokémon known as the 'Order Pokémon'. Who am I?", "answer": "Zygarde"},
            {"q": "I am the mythical Pokémon that evolves into multiple Eeveelutions. Who am I?", "answer": "Eevee"},
            {"q": "I am the legendary Pokémon of Hoenn, representing the ozone layer. Who am I?", "answer": "Rayquaza"},
            {"q": "I am a Pokémon that appears only when you have a special flute. Who am I?", "answer": "Arceus"},
            {"q": "I am the legendary Pokémon that shaped Sinnoh’s lakes. Who am I?", "answer": "Azelf"},
            {"q": "I am the Pokémon known as the 'Lunar Pokémon'. Who am I?", "answer": "Cresselia"},
            {"q": "I am the legendary Pokémon of Kalos with a tree-like appearance. Who am I?", "answer": "Xerneas"},
            {"q": "I am the legendary Pokémon that represents destruction in Kalos. Who am I?", "answer": "Yveltal"},
        ],
    },
    "Real Problem":{
        "Easy": [
            {"q": "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?", "answer": "map"},
            {"q": "What has one head, one foot, and four legs?", "answer": "bed"},
            {"q": "What has hands but cannot clap?", "answer": "clock"},
            {"q": "What has ears but cannot hear?", "answer": "cornfield"},
            {"q": "What has a neck but no head?", "answer": "bottle"},
            {"q": "What has a bed but never sleeps?", "answer": "river"},
            {"q": "What has branches but no fruit or leaves?", "answer": "bank"},
            {"q": "What has wheels but cannot move by itself?", "answer": "wheelbarrow"},
            {"q": "What comes down but never goes up?", "answer": "rain"},
            {"q": "What belongs to you but others use it more than you?", "answer": "your name"},
            {"q": "What has teeth but cannot bite?", "answer": "comb"},
            {"q": "What has an eye but cannot see?", "answer": "needle"},
            {"q": "What has holes but still holds water?", "answer": "sponge"},
            {"q": "What can be cracked, made, told, and played?", "answer": "joke"},
            {"q": "What gets sharper the more you use it?", "answer": "brain"},
            {"q": "What has four legs but no body?", "answer": "table"},
            {"q": "What has a face but no eyes?", "answer": "clock"},
            {"q": "What has a ring but no finger?", "answer": "telephone"},
            {"q": "What can you break without touching?", "answer": "promise"},
            {"q": "What is easy to lift but hard to throw?", "answer": "feather"},
            {"q": "What has keys but cannot open locks?", "answer": "piano"},
            {"q": "What has letters but is not alive?", "answer": "alphabet"},
            {"q": "What has roots but never grows?", "answer": "mountain"},
            {"q": "What has bark but cannot bite?", "answer": "tree"},
            {"q": "What gets wetter the more it dries?", "answer": "towel"},
            {"q": "What has many stories but no words?", "answer": "building"},
            {"q": "What has fingers but no hand?", "answer": "glove"},
            {"q": "What has an end but no beginning?", "answer": "stick"},
            {"q": "What has no life but can die?", "answer": "battery"},
            {"q": "What comes once in a minute, twice in a moment, but never in a thousand years?", "answer": "letter M"},
        ],
        "Medium": [
            {"q": "What has an eye, but cannot see?", "answer": "needle"},
            {"q": "The more you take away from me, the larger I become. What am I?", "answer": "a hole"},
            {"q": "What begins with an E, ends with an E, but only contains one letter?", "answer": "envelope"},
            {"q": "What is always in front of you but can’t be seen?", "answer": "future"},
            {"q": "What gets wetter the more it dries?", "answer": "towel"},
            {"q": "What has to be broken before it can be used?", "answer": "egg"},
            {"q": "What can you catch but not throw?", "answer": "cold"},
            {"q": "What has a tongue but never speaks?", "answer": "shoe"},
            {"q": "What comes at night but disappears by morning?", "answer": "stars"},
            {"q": "What gets bigger the more you take away from it?", "answer": "hole"},
            {"q": "What is always moving but never goes anywhere?", "answer": "time"},
            {"q": "What has no beginning, middle, or end?", "answer": "circle"},
            {"q": "What has a heart but no body?", "answer": "artichoke"},
            {"q": "What has no wings but can fly?", "answer": "time"},
            {"q": "What can travel without moving?", "answer": "map"},
            {"q": "What runs around the house but never moves?", "answer": "fence"},
            {"q": "What is always coming but never arrives?", "answer": "tomorrow"},
            {"q": "What has no eyes but can cry?", "answer": "cloud"},
            {"q": "What has many rings but no fingers?", "answer": "tree"},
            {"q": "What has roots that nobody sees, taller than trees?", "answer": "mountain"},
            {"q": "What has no voice but makes sound?", "answer": "echo"},
            {"q": "What disappears the moment you say its name?", "answer": "silence"},
            {"q": "What is as light as a feather but no one can hold it for long?", "answer": "breath"},
            {"q": "What has legs but cannot walk?", "answer": "chair"},
            {"q": "What comes at the end of everything?", "answer": "letter G"},
            {"q": "What can be measured but has no substance?", "answer": "time"},
            {"q": "What can run but has no legs?", "answer": "river"},
            {"q": "What has many teeth but cannot eat?", "answer": "comb"},
            {"q": "What has a shadow but no body?", "answer": "reflection"},
            {"q": "What is seen in the water but never gets wet?", "answer": "reflection"},
        ],
        "Hard": [
            {"q": "What is seen in the middle of March and April that can’t be seen at the beginning or end of either month?", "answer": "letter R"},
            {"q": "I am taken from a mine, locked up in a wooden case, never released but used by many. What am I?", "answer": "pencil lead"},
            {"q": "Forward I am heavy, backward I am not. What am I?", "answer": "ton"},
            {"q": "The more of me you take, the more you leave behind. What am I?", "answer": "footsteps"},
            {"q": "I am not alive, but I can die. What am I?", "answer": "battery"},
            {"q": "What has no body but can be heard?", "answer": "echo"},
            {"q": "What has no life but can grow?", "answer": "crystal"},
            {"q": "What breaks but never falls, and what falls but never breaks?", "answer": "day and night"},
            {"q": "What has keys but no locks, and space but no room?", "answer": "keyboard"},
            {"q": "What can be cracked, made, told, and played?", "answer": "joke"},
            {"q": "What is so fragile that saying its name breaks it?", "answer": "silence"},
            {"q": "I am the beginning of everything and the end of time and space. What am I?", "answer": "letter E"},
            {"q": "What occurs once in a lifetime, twice in a moment, but never in a century?", "answer": "letter M"},
            {"q": "What gets sharper the more it’s used?", "answer": "brain"},
            {"q": "What has to be given before it can be taken?", "answer": "advice"},
            {"q": "What is always on its way here but never arrives?", "answer": "tomorrow"},
            {"q": "What can you find in the middle of nowhere?", "answer": "letter H"},
            {"q": "What can you see once in a year, twice in a week, and never in a day?", "answer": "letter E"},
            {"q": "What is always moving yet never leaves its place?", "answer": "clock"},
            {"q": "I am not alive, but I can die if not charged. What am I?", "answer": "battery"},
            {"q": "What gets older the more time you take from it?", "answer": "photograph"},
            {"q": "What is invisible but can be felt when it moves?", "answer": "air"},
            {"q": "What can’t be used until it’s broken?", "answer": "egg"},
            {"q": "What is so light it can be carried by wind but so heavy it crushes ships?", "answer": "iceberg"},
            {"q": "What is harder to catch the faster you run?", "answer": "your breath"},
            {"q": "What comes at the end of a rainbow?", "answer": "letter W"},
            {"q": "What has no feet but leaves tracks?", "answer": "snail"},
            {"q": "What is always in motion but never goes anywhere?", "answer": "time"},
            {"q": "What is everywhere but seen nowhere?", "answer": "air"},
            {"q": "What is always lost but never found?", "answer": "time"},
        ],
    },
}
